[project]
name = "equity-research-analyst"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dheeraj Chavan", email = "chavandheeraj165@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
equity-research-analyst = "equity_research_analyst:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = ["."]

